-- ============================================================================
-- SCHEMA รวมศูนย์ของฐานข้อมูล (Single Source of Truth สำหรับการออกแบบตาราง)
-- โครงงานเกมการ์ดเสริมสร้างแนวคิดระบบสารสนเทศ | Supabase (PostgreSQL)
--
-- ไฟล์นี้รวบรวม "นิยามตารางทั้งหมด" ไว้ที่เดียวเพื่อใช้อ้างอิง/จัดทำเอกสาร
-- (ภาคผนวกการออกแบบฐานข้อมูล) เรียงตามลำดับการพึ่งพา (dependency order)
--
-- หมายเหตุ: ตรรกะฝั่ง server (RPC functions, triggers, policy เต็ม) ยังคงอยู่
-- ในไฟล์ deploy แยกตามระบบ — ไฟล์นี้สรุป RLS แบบย่อและชี้แหล่งอ้างอิงไว้ให้
--
--   ตาราง                แหล่ง deploy จริง
--   ───────────────────  ────────────────────────────────────────────
--   player_profiles      player_profiles.sql + player_profiles_lock.sql
--   rooms                Docs/supabase_schema.sql + rooms_rls.sql
--   matchmaking_queue    Docs/supabase_schema.sql (+ claim/cancel RPC)
--   shop_items           shop_quiz_schema.sql
--   daily_quiz_claims    shop_quiz_schema.sql
--   quiz_patches         migrations/20260521_quiz_patch_system.sql
--   quiz_questions       migrations/20260521_quiz_patch_system.sql
--   otp_codes            otp_schema.sql
-- ============================================================================

create extension if not exists pgcrypto;

-- ════════════════════════════════════════════════════════════════════════════
-- 1) player_profiles — โปรไฟล์ผู้เล่นหลัก (สกุลเงิน, สถิติ, อันดับ, ไอเทมตกแต่ง)
--    id : 1:1 กับ auth.users(id) | เขียนได้เฉพาะ service_role (Edge Functions)
--    RLS: เปิด — client (authenticated) อ่านได้อย่างเดียว ดู player_profiles_lock.sql
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.player_profiles (
    id                 uuid        not null
                                   references auth.users (id) on delete cascade,
    username           text        not null default 'Player',
    gems               integer     not null default 0,
    mmr                integer     not null default 1000,
    wins               integer     not null default 0,
    losses             integer     not null default 0,
    owned_frames       text[]      not null default array['frame_default']::text[],
    equipped_frame     text        not null default 'frame_default',
    selected_character integer              default 0,
    updated_at         timestamptz not null default now(),
    constraint player_profiles_pkey primary key (id)
);

-- ════════════════════════════════════════════════════════════════════════════
-- 2) rooms — ห้องเกมที่ระบบจับคู่สร้างขึ้น (ผูกกับ Photon session)
--    RLS: เปิด (deploy/policy เต็มอยู่ที่ rooms_rls.sql)
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.rooms (
    id           bigint generated by default as identity primary key,
    room_code    text not null,
    session_name text not null,
    host_name    text not null,
    player_count integer not null default 1,
    status       text not null default 'waiting',
    created_at   timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_rooms_room_code
    on public.rooms (room_code);
create index if not exists idx_rooms_status_created_at
    on public.rooms (status, created_at);

-- ════════════════════════════════════════════════════════════════════════════
-- 3) matchmaking_queue — คิวจับคู่ผู้เล่นออนไลน์
--    RPC claim_matchmaking_room / cancel_matchmaking_search อยู่ที่
--    Docs/supabase_schema.sql (server-authoritative matchmaking)
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.matchmaking_queue (
    id                  uuid primary key default gen_random_uuid(),
    player_id           text not null,
    status              text not null default 'waiting',
    room_code           text null,
    room_id             bigint null references public.rooms (id) on delete set null,
    target_player_count integer not null default 2,
    search_request_id   text not null,
    created_at          timestamptz not null default timezone('utc', now()),
    matched_at          timestamptz null,
    constraint matchmaking_queue_target_player_count_check
        check (target_player_count in (2, 3, 4))
);

create index if not exists idx_matchmaking_queue_status_target_created_at
    on public.matchmaking_queue (status, target_player_count, created_at);
create index if not exists idx_matchmaking_queue_player_search
    on public.matchmaking_queue (player_id, search_request_id);
create unique index if not exists uq_matchmaking_queue_waiting_player
    on public.matchmaking_queue (player_id)
    where status = 'waiting';

-- ════════════════════════════════════════════════════════════════════════════
-- 4) shop_items — ราคาไอเทมร้านค้า (source of truth — client ปลอมราคาไม่ได้)
--    RLS: เปิด — อ่านได้ทุกคน, เขียนได้เฉพาะ service_role
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.shop_items (
    item_id text primary key,
    price   int  not null check (price >= 0)
);

-- ════════════════════════════════════════════════════════════════════════════
-- 5) daily_quiz_claims — กันรับรางวัลควิซรายวันซ้ำ (1 คน/วัน)
--    RLS: เปิด — ไม่มี policy client => เข้าถึงได้เฉพาะ service_role
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.daily_quiz_claims (
    user_id    uuid not null references auth.users(id) on delete cascade,
    claim_date date not null,
    created_at timestamptz not null default now(),
    primary key (user_id, claim_date)
);

-- ════════════════════════════════════════════════════════════════════════════
-- 6) quiz_patches — metadata ของแต่ละชุด/แพ็กคำถามควิซ
--    RLS: เปิด — อ่านได้เฉพาะ patch ที่ is_active = true
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.quiz_patches (
    id              bigserial   primary key,
    name            text        not null,
    description     text        default '',
    is_active       boolean     not null default true,
    total_questions integer     not null default 0,   -- อัปเดตอัตโนมัติด้วย trigger
    created_at      timestamptz not null default timezone('utc', now()),
    updated_at      timestamptz not null default timezone('utc', now())
);

create index if not exists idx_quiz_patches_active
    on public.quiz_patches(is_active)
    where is_active = true;

-- ════════════════════════════════════════════════════════════════════════════
-- 7) quiz_questions — คลังคำถามควิซทั้งหมด (ผูกกับ quiz_patches)
--    RLS: เปิด — อ่านได้เฉพาะคำถามที่อยู่ใน patch ที่ active
--    Triggers/RPC (get_active_questions, import_quiz_patch) อยู่ที่
--    migrations/20260521_quiz_patch_system.sql
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.quiz_questions (
    id            bigserial   primary key,
    patch_id      bigint      not null references public.quiz_patches(id) on delete cascade,
    external_id   text        default '',
    category      text        not null default 'ทั่วไป',
    difficulty    text        not null default 'medium'
                              check (difficulty in ('easy', 'medium', 'hard')),
    question      text        not null,
    choices       jsonb       not null,                 -- array 4 ตัวเลือก
    correct_index smallint    not null check (correct_index between 0 and 3),
    created_at    timestamptz not null default timezone('utc', now())
);

create index if not exists idx_quiz_questions_patch_id
    on public.quiz_questions(patch_id);

-- ════════════════════════════════════════════════════════════════════════════
-- 8) otp_codes — รหัส OTP ยืนยันอีเมล (custom OTP system)
--    RLS: เปิด — ไม่มี policy client => เข้าถึงได้เฉพาะ service_role (Edge Function)
-- ════════════════════════════════════════════════════════════════════════════
create table if not exists public.otp_codes (
    id         uuid        primary key default gen_random_uuid(),
    email      text        not null,
    code_hash  text        not null,                     -- SHA-256 ของโค้ด (ไม่เก็บเลขตรง)
    expires_at timestamptz not null,
    attempts   int         not null default 0,
    used       boolean     not null default false,
    created_at timestamptz not null default now()
);

create index if not exists idx_otp_email_created
    on public.otp_codes (email, created_at desc);
